# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '挑战失败背景.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class Ui_Shi_Bai(QMainWindow):
    def setupUi(self, Shi_Bai):
        Shi_Bai.setObjectName("Shi_Bai")
        Shi_Bai.resize(308, 266)
        Shi_Bai.setWindowFlags(QtCore.Qt.FramelessWindowHint|QtCore.Qt.WindowStaysOnTopHint)
        font = QtGui.QFont()
        font.setFamily("楷体")
        Shi_Bai.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/小窗口图标/图片文件夹/挑战失败.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Shi_Bai.setWindowIcon(icon)
        Shi_Bai.setWindowOpacity(0.9)
        Shi_Bai.setStyleSheet("#Shi_Bai{border-image: url(:/小窗口图标/图片文件夹/挑战失败背景.jpg);}")
        # 使窗口居中
        screen = QDesktopWidget().screenGeometry()
        size = self.geometry()
        newLeft = (screen.width() - size.width()) // 2
        newTop = (screen.height() - size.height()) // 2
        self.move(newLeft, newTop)
        self.lable = QtWidgets.QLabel(Shi_Bai)
        self.lable.setGeometry(QtCore.QRect(0, 200, 301, 61))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.lable.setFont(font)
        self.lable.setStyleSheet("color: rgb(255, 0, 0);")
        self.lable.setAlignment(QtCore.Qt.AlignCenter)
        self.lable.setObjectName("lable")

        self.retranslateUi(Shi_Bai)
        QtCore.QMetaObject.connectSlotsByName(Shi_Bai)

    def retranslateUi(self, Shi_Bai):
        _translate = QtCore.QCoreApplication.translate
        Shi_Bai.setWindowTitle(_translate("Shi_Bai", "挑战失败"))
        self.lable.setText(_translate("Shi_Bai", "输入框"))
    def __init__(self):
        super(Ui_Shi_Bai, self).__init__()
        self.setupUi(self)
